### ISSUE TITLE
Minor bug found

### ISSUE THREAD

**Issue by nathankahn60** [RensTillmann/wc-confirm-shipping-address-before-placing-order#1]
Thank you for this plugin, I appreciate it very much.  I just want to tell you about a bug I found, in case you should work on this project again in the future, you will know about it.  At the checkout page, near the Place Order button, is a checkbox "I have read and agree to the website terms and conditions *"   If I leave this box unchecked, and Place Order, your confirmation screen comes, and I say yes the address is good.  And I am returned to the Checkout page with no explanation.  And I click Place Order again and I confirm the address again and I'm returned to the checkout page. again  Until I check the box for agree to terms, and then I Place Order, and then I confirm the address, and then the order is placed.  Of course the customer should check the box always, but in case he doesn't, it will be a little confusing until he realizes.  So I just wanted to inform you about it.

**Comment by RensTillmann** [comment]
Hi, should be fixed in v1.0.1
